# Generated by Utopia Compiler - x86_64 Assembly Backend
# Ultimate performance native machine code
.intel_syntax noprefix
.text
.global _start
.global main

.section .data
    msg_hello: .ascii "Hello from Utopia!\n"
    msg_hello_len = . - msg_hello

.section .text

main:
    push rbp
    mov rbp, rsp
    
    # Your Utopia code here
    mov rax, 42  # Return value
    
    pop rbp
    ret

_start:
    call main
    mov rdi, rax  # Exit code
    mov rax, 60   # sys_exit
    syscall
